<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;

class UserRepository extends EntityRepository
{
    public function getMedewerkers($a)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery("SELECT u FROM AppBundle:User u WHERE u.afdeling =:afdeling");

        $query->setParameter('afdeling', $a);

        return $query->getResult();
    }
}
