<?php

namespace AppBundle\Repository\Entity;

/**
 * AfdelingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfdelingRepository extends \Doctrine\ORM\EntityRepository
{
}
