<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH3prqxy\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH3prqxy/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerH3prqxy.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerH3prqxy\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerH3prqxy\appDevDebugProjectContainer(array(
    'container.build_hash' => 'H3prqxy',
    'container.build_id' => '00f17b4c',
    'container.build_time' => 1522233204,
));
